# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('game', 'player', 'frame', 'attempt')]),
        ),
    ]
